# Generated by Django 3.0.1 on 2019-12-27 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CivilType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenderType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('idDocument', models.CharField(max_length=200, unique=True)),
                ('celphone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('adress', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel.ScheduleState')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('born', models.DateField()),
                ('year', models.IntegerField()),
                ('checkIn', models.DateField()),
                ('civilType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel.CivilType')),
                ('documentType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel.DocumentType')),
                ('genderType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel.GenderType')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='personnel.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='personnel.Person')),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='personnel.Schedule')),
            ],
        ),
    ]
