# Generated by Django 3.0.1 on 2019-12-27 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='adress',
            new_name='address',
        ),
    ]
