# Generated by Django 3.0.1 on 2019-12-27 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_auto_20191227_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='civilType',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='personnel.CivilType'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='genderType',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='personnel.GenderType'),
        ),
    ]
