# Generated by Django 3.0.1 on 2019-12-28 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0007_auto_20191228_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='civilType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='personnel.CivilType'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='genderType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='personnel.GenderType'),
        ),
    ]
