# Generated by Django 3.0.1 on 2019-12-28 19:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0008_auto_20191228_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='hour',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
