# Generated by Django 3.0.1 on 2019-12-29 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0010_auto_20191228_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='schedule',
        ),
        migrations.AddField(
            model_name='schedule',
            name='doctor',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='personnel.Doctor'),
            preserve_default=False,
        ),
    ]
