# Generated by Django 3.0.1 on 2019-12-29 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0012_auto_20191229_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='civilType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='personnel.CivilType'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='documentType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='personnel.DocumentType'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='genderType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='personnel.GenderType'),
        ),
    ]
