# Generated by Django 3.0.1 on 2020-01-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('brand', models.CharField(max_length=200)),
                ('representation', models.CharField(max_length=200)),
                ('stock', models.IntegerField()),
                ('register', models.CharField(max_length=200)),
                ('risk', models.CharField(max_length=200)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
