# Generated by Django 3.0.1 on 2019-12-29 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0013_auto_20191229_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalTreatments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('deleted', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='personnel.Patient')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.TreatmentState')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='treatment.Treatment')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistance', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('deleted', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='personnel.Patient')),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='personnel.Schedule')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='treatment.Treatment')),
            ],
        ),
    ]
