# Generated by Django 3.0.1 on 2019-12-29 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0013_auto_20191229_1440'),
        ('treatment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalTreatments',
            new_name='HistoricalTreatment',
        ),
    ]
