# Generated by Django 3.0.1 on 2019-12-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0002_auto_20191229_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
