# Generated by Django 3.0.1 on 2020-01-01 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0014_auto_20191229_1908'),
        ('treatment', '0005_auto_20191230_1829'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalTreatment',
            new_name='TreatmentHistory',
        ),
    ]
