# Generated by Django 3.0.1 on 2020-01-01 10:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0014_auto_20191229_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associate_with', models.CharField(max_length=200)),
                ('associate_celphone', models.IntegerField()),
                ('reason', models.CharField(max_length=200)),
                ('disease', models.CharField(max_length=200)),
                ('antecedent', models.CharField(max_length=200)),
                ('family_antecedent', models.CharField(max_length=200)),
                ('surgical_antecedent', models.CharField(max_length=200)),
                ('pathological_antecedent', models.CharField(max_length=200)),
                ('pharm_antecedent', models.CharField(max_length=200)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conset_date', models.DateField(default=datetime.datetime(2020, 1, 1, 10, 50, 33, 914373))),
                ('usage_date', models.DateField(default=datetime.datetime(2020, 1, 1, 10, 50, 33, 914373))),
                ('description', models.TextField()),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('deleted', models.BooleanField(default=False)),
                ('basic_info', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='medicalHistory.BasicInfo')),
                ('consent', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='medicalHistory.Consent')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='personnel.Patient')),
            ],
        ),
    ]
