# Generated by Django 3.0.1 on 2020-01-01 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalHistory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consent',
            name='conset_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 1, 10, 52, 15, 382361)),
        ),
        migrations.AlterField(
            model_name='consent',
            name='usage_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 1, 10, 52, 15, 382361)),
        ),
    ]
