# Generated by Django 3.0.1 on 2020-01-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalHistory', '0002_auto_20200101_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consent',
            name='conset_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='consent',
            name='usage_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
