# Generated by Django 3.0.1 on 2020-01-01 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0014_auto_20191229_1908'),
        ('medicalHistory', '0003_auto_20200101_1053'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalPerson',
            new_name='MedicalHistory',
        ),
    ]
